// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperSize } from "./PaperSize";
import type { PdfStandard } from "./PdfStandard";
import type { SlideRange } from "./SlideRange";

/**
 * Options controlling the conversion process.
 */
export type ConvertOptions = { 
/**
 * Filter XLSX sheets by name. Only sheets whose names are in this list
 * are included, hidden ones among them. If `None`, every sheet the
 * workbook does not hide is included — Excel prints no `hidden` or
 * `veryHidden` sheet.
 */
sheet_names: Array<string> | null, 
/**
 * Filter PPTX slides by range (1-indexed). If `None`, all slides are included.
 */
slide_range: SlideRange | null, 
/**
 * PDF standard to enforce. If `None`, produces a standard PDF 1.7.
 */
pdf_standard: PdfStandard | null, 
/**
 * Override paper size for the output PDF. If `None`, uses the source document's size.
 */
paper_size: PaperSize | null, 
/**
 * Additional font directories to search for fonts.
 */
font_paths: Array<string>, 
/**
 * Standalone font or font-collection bytes to make available during this
 * conversion. In-memory fonts work on native and WASM targets and take
 * priority over filesystem and bundled fallback fonts.
 */
font_bytes: Array<Uint8Array>,
/**
 * Family to append as the final candidate in every generated font chain.
 * This lets a caller-provided face cover glyphs that none of the
 * document's declared families or built-in substitutes can render.
 */
last_resort_font_family: string | null,
/**
 * Force landscape orientation. If `Some(true)`, swaps width/height so width > height.
 * If `Some(false)`, forces portrait. If `None`, uses source document orientation.
 */
landscape: boolean | null, 
/**
 * Enable tagged PDF output with document structure tags (H1-H6, P, Table, Figure).
 * When `true`, the output PDF includes accessibility tags that map document
 * structure for screen readers and assistive technologies.
 */
tagged: boolean, 
/**
 * Enable PDF/UA (Universal Accessibility) compliance. Implies `tagged: true`.
 * Combines tagged PDF with the PDF/UA-1 standard for full accessibility compliance.
 */
pdf_ua: boolean,
/**
 * Enable bounded-layout mode for large XLSX files.
 * XLSX rows are parsed into IR, then compiled in page-aligned chunks to
 * bound peak Typst layout memory.
 * Each chunk is compiled independently and the resulting PDFs are merged.
 * Requires the `pdf-ops` feature for PDF merging.
 */
streaming: boolean,
/**
 * Target row count for each streaming compilation chunk. The converter
 * extends a chunk to the end of its current PDF page. Defaults to 1000 if `None`.
 * Only used when `streaming` is `true`.
 */
streaming_chunk_size: number | null, };
